<?php $this->appendCss("/css/atp-comic/comic.less")?>

<div id="archives">
	<?php foreach($arcs as $arc) { ?>
		<h2>
			<?=$arc->displayName()?> - Archives
		</h2>
		
		<?php if(count($arc->getSubArcs()) == 0) { ?>
            <?=$this->render('atp-comic/shared/archive-page-links.phtml', array('arc' => $arc))?>
		<?php } else { ?>
			<ul class="sub-arcs">
				<?php foreach($arc->getSubArcs() as $index => $subArc) { ?>
					<li>
						<h3>
							<?=$arc->subArcName?> <?=$index + 1?> - <?=$subArc->name?>
							<?php if(count($subArc->getSubArcs()) > 1) { ?>
								<div class="browse-by-subarc">
									(<a href="<?=$this->url("comic/archives", array('arc' => $subArc->url))?>">
										browse this <?=strtolower($arc->subArcName)?> by <?=strtolower($subArc->subArcName)?>
									</a>)
								</div>
							<?php } ?>
						</h3>
                        <?=$this->render('atp-comic/shared/archive-page-links.phtml', array('arc' => $subArc))?>
					</li>
				<?php } ?>
			</ul>
		<?php } ?>
	<?php } ?>
	
	<div style="clear: both;"></div>
	
	{{block:archives-blurb}}
</div>