<?php $this->appendCss("/css/atp-comic/comic.less")?>

<div id="archives">
    <img class="arc-banner" src="http://<?=$this->siteParam("comic-s3-bucket")?>/<?=$this->s3FileName($arc->banner)?>" />
    <h1>
        <?php if($arc) {?>
            <?=$arc->name?>
        <?php } ?>
    </h1>

    <div class="arc-summary"><?=$arc->summaryHtml?></div>
    <?php if($this->siteParam("comic-show-archive-breadcrumbs")) {?>
        <ol class="breadcrumb">
            <?php foreach($arc->parents as $parentArc) { ?>
                <li>
                    <a
                        href="<?=$this->url("comic/archives", array('arc' => $parentArc->url))?>"
                        <?php if($parentArc->url === $arc->url) {?> class="active" <?php } ?>
                    >
                        <?=$parentArc->name?>
                    </a>
                </li>
            <?php } ?>
        </ol>
    <?php } ?>

    <?php if(count($arc->pages) > 0) { ?>
        <div class="arc-pages">
            <ul class="arc-pages">
                <?php foreach($arc->pages as $page) { ?>
                    <li>
                        <?=$this->render('atp-comic/shared/archive-page-link.phtml', array('page' => $page))?>
                    </li>
                <?php } ?>
            </ul>
        </div>
    <?php } ?>

    <ul class="sub-arcs">
        <?php foreach($arc->subArcs as $index => $subArc) { ?>
            <li>
                <a href="<?=$this->url("comic/archives", array('arc' => $subArc->url))?>">
                    <img class="subarc-thumbnail" src="http://<?=$this->siteParam("comic-s3-bucket")?>/<?=$this->s3FileName($subArc->thumbnail)?>" />
                    <div class="subarc-info">
                        <?=$subArc->name?>
                    </div>
                </a>
            </li>
        <?php } ?>
    </ul>

	<div style="clear: both;"></div>
</div>
