<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0">
    <channel>
        <title><?=$arc->name?> RSS Feed</title>
        <description></description>
        <link><?=$this->serverUrl($this->url('comic/archives', ['arc' => $arc->url]))?></link>
        <lastBuildDate><?=$nodes[0]->page->postDate?></lastBuildDate>
        <pubDate><?=$nodes[0]->page->postDate?></pubDate>
        <ttl>1800</ttl>

        <?php foreach($nodes as $node) {?>
            <item>
                <title><?=$arc->name?> Page <?=$node->pageNumber?>: <?=$node->page->title?></title>
                <description></description>
                <link><?=$this->serverUrl($this->url('comic/page', $node->getRoutingData()))?></link>
                <pubDate><?=$node->page->postDate?></pubDate>
            </item>
        <?php } ?>
    </channel>
</rss>