<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0">
    <channel>
        <title><?=$this->siteParam('core-site-title')?> RSS Feed</title>
        <description></description>
        <link><?=$this->serverUrl($this->url('comic/archives', ['arc' => $arc]))?></link>
        <lastBuildDate><?=$pages[0]->postDate?></lastBuildDate>
        <pubDate><?=$pages[0]->postDate?></pubDate>
        <ttl>1800</ttl>

        <?php foreach($pages as $page) {?>
            <item>
                <title><?=$this->siteParam('core-site-title')?>: <?=$page->name?></title>
                <description></description>
                <link><?=$this->serverUrl($this->url('comic/page', ['pageUrl' => $page->url]))?></link>
                <pubDate><?=$page->postDate?></pubDate>
            </item>
        <?php } ?>
    </channel>
</rss>