<?php $this->headTitle($arc->name)?>
<?php $this->headTitle($page->title)?>
<?php $this->appendJs("/atp-comic/js/comic.js")?>

<img class="comic-img" src="<?=$page->filePath('image_file')?>" />
<h1 class="page-title"><?=$page->title?> (page <?=$page->pageNumber?>)</h1>

<div class="current-arc-links arc-links"><?=$this->partial('atp-comic/shared/nav_links.phtml', array('node' => $node))?></div>

<div class="all-arc-links arc-links">
	<?php foreach($page->getAtpcomicNodesByPage() as $curNode) { ?>
		<?=$this->partial('atp-comic/shared/nav_links.phtml', array('node' => $curNode))?>
	<?php } ?>
</div>
