<div class="comic-nav-links-container">
    <ul class="comic-nav-links">
        <?php if($page->id !== $page->firstPage->id) { ?>
            <li class="first-page-link">
                <a href="<?=$this->url('comic/page', ['pageUrl' => $page->firstPage->url])?>">
                    <i></i>
                </a>
            </li>
            <li class="prev-page-link">
                <a href="<?=$this->url('comic/page', ['pageUrl' => $page->prevPage->url])?>">
                    <i></i>
                </a>
            </li>
        <?php } else { ?>
            <li class="arc-link prev-arc-link"></li>
        <?php } ?>
        <li class="arc-page-list">
            <a href="<?=$this->url('comic/archives', ['arc' => $page->arc->url])?>" title="Archives">
                <span>Archives</span>
                <i></i>
            </a>
        </li>
        <?php if($page->id !== $page->lastPage->id) { ?>
            <li class="next-page-link">
                <a href="<?=$this->url('comic/page', ['pageUrl' => $page->nextPage->url])?>">
                    <i></i>
                </a>
            </li>
            <li class="last-page-link">
                <a href="<?=$this->url('comic/page', ['pageUrl' => $page->lastPage->url])?>">
                    <i></i>
                </a>
            </li>
        <?php } else { ?>
            <li class="arc-link next-arc-link"></li>
        <?php } ?>
    </ul>
</div>
<?php if($this->siteParam('comic-show-archive-dropdown')) { ?>
    <div class="archive-dropdown">
        <select>
            <option data-url=""><?=$node->arc->name?></option>
            <?php foreach($node->arc->getPageNodes() as $curNode) { ?>
                <option data-url="<?=$this->url("comic/page", $curNode->getRoutingData())?>">(<?=$curNode->pageNumber?>) <?=$curNode->page->title?></option>
            <?php } ?>
        </select>
    </div>
<?php } ?>
