<ul class="comic-nav-links">
	<?php if(!$node->isFirst()) { ?>
		<li class="first-page-link">
			<a href="<?=$this->url('comic/page', $node->arc->firstNode()->getRoutingData())?>">
                <i></i>
            </a>
		</li>
		<li class="prev-page-link">
			<a href="<?=$this->url('comic/page', $node->prevNode()->getRoutingData())?>">
                <i></i>
            </a>
		</li>
	<?php } else { ?>
		<li class="arc-link prev-arc-link">
			<?php if($node->hasPrevArc()) { ?>
				<a href="<?=$this->url('comic/page', $node->arc->prevArc->lastNode()->getRoutingData())?>">
                    <i></i> <?=$node->arc->prevArc->displayName()?>
                </a>
			<?php } ?>
		</li>
	<?php } ?>
	<li class="arc-page-list">
        <a href="<?=$this->url('comic/archives', array('arc' => $node->arc->url))?>" title="<?=$node->arc->fullName()?>">
            <span>Archives</span>
            <i></i>
        </a>
	</li>
	<?php if(!$node->isLast()) { ?>
		<li class="next-page-link">
			<a href="<?=$this->url('comic/page', $node->nextNode()->getRoutingData())?>">
                <i></i>
            </a>
		</li>
		<li class="last-page-link">
			<a href="<?=$this->url('comic/page', $node->arc->lastNode()->getRoutingData())?>">
                <i></i>
            </a>
		</li>
	<?php } else { ?>
		<li class="arc-link next-arc-link">
			<?php if($node->hasNextArc()) { ?>
				<a href="<?=$this->url('comic/page', $node->arc->nextArc->firstNode()->getRoutingData())?>">
                    <?=$node->arc->nextArc->displayName()?> <i></i>
                </a>
			<?php } else { ?>
                &nbsp;
            <?php } ?>
		</li>
	<?php } ?>
</ul>
<?php if($this->siteParam('comic-show-archive-dropdown')) { ?>
    <div class="archive-dropdown">
        <select>
            <option data-url=""><?=$node->arc->name?></option>
            <?php foreach($node->arc->getPageNodes() as $curNode) { ?>
                <option data-url="<?=$this->url("comic/page", $curNode->getRoutingData())?>">(<?=$curNode->pageNumber?>) <?=$curNode->page->title?></option>
            <?php } ?>
        </select>
    </div>
<?php } ?>
