<?php $this->appendJs("/atp-comic/js/comic.js")?>
<?php $this->appendCss("/css/atp-comic/comic.less")?>

<div class="comic-page-widget">
    <p class="page-name">
        <em><a href="<?=$this->url('comic/archives', array('arc' => $node->arc->url))?>" title="<?=$node->arc->fullName()?>">
                <?=$node->arc->name?>
        </a></em>, page <?=$node->pageNumber?>
    </p>

    <?php if($this->siteParam("comic-show-nav-links-top")) { ?>
		<?=$navLinks?>
	<?php } ?>

	<img class="comic-img" src="<?=$this->basePath($node->page->filePath('image_file'))?>" />

    <h1 class="page-title"><?=$node->page->title?></h1>

	<?php if($this->siteParam("comic-show-nav-links-bottom")) { ?>
		<?=$navLinks?>
	<?php } ?>

	<?php if($this->siteParam("comic-use-adsense")) { ?>
		<div class="ad-container">
			<div class="ad"><?=$this->adsense("inline-ad")?></div>
		</div>
	<?php } ?>

    <div class="comic-page-footer">
        <div class="page-extra">
            <div class="commentary">
                <h2>Commentary</h2>
                <div class="body">
                    <?php if(strlen($node->page->descriptionHtml) > 0) { ?>
                        <?=$node->page->descriptionHtml?>
                    <?php } else { ?>
                        <em>&lt;No page commentary.&gt;</em>
                    <?php } ?>
                </div>
            </div>
        </div>

        <?php if(strlen($node->page->transcriptHtml) > 0) { ?>
            <script>var showTranscripts=<?=$this->siteParam('comic-show-transcripts') || true?>;</script>
            <div class="page-extra">
                <div class="transcript">
                    <h2>Transcript</h2>
                    <div class="body">
                        <?=$node->page->transcriptHtml?>
                    </div>
                </div>
            </div>
        <?php } ?>
    </div>
</div>