<?php $this->appendJs("/atp-comic/js/comic.js")?>
<?php $this->appendCss("/atp-comic/css/comic.less")?>

<div class="comic-page-widget">
    <p class="page-name">
        <em><a href="<?=$this->url('comic/archives', array('arc' => $node->arc->url))?>" title="<?=$node->arc->fullName()?>">
                <?=$node->arc->name?>
        </a></em>, page <?=$node->pageNumber?>
    </p>

    <?php if($this->siteParam("comic-show-nav-links-top")) { ?>
		<?=$navLinks?>
	<?php } ?>

	<img class="comic-img" src="<?=$this->basePath($node->page->filePath('image_file'))?>" />

    <h1 class="page-title"><?=$node->page->title?></h1>

	<?php if($this->siteParam("comic-show-nav-links-bottom")) { ?>
		<?=$navLinks?>
	<?php } ?>

	<?php if($this->siteParam("comic-use-adsense")) { ?>
		<div class="ad-container">
			<div class="ad"><?=$this->adsense("inline-ad")?></div>
		</div>
	<?php } ?>

    <?php if(strlen($node->page->transcriptHtml) > 0) { ?>
        <script>var showTranscripts=<?=$this->siteParam('comic-show-transcripts') || true?>;</script>
        <div class="transcript">
            <div class="panel panel-default">
                <div class="panel-heading" title="Click to show page transcript">Transcript</div>
                <p class="panel-body"><?=$node->page->transcriptHtml?></p>
            </div>
        </div>
    <?php } ?>

	<div class="commentary">
        <div class="panel panel-default">
            <div class="panel-heading">Commentary</div>
            <div class="panel-body">
                <?php if(strlen($node->page->descriptionHtml) > 0) { ?>
                    <?=$node->page->descriptionHtml?>
                <?php } else { ?>
                    <em>&lt;No page commentary.&gt;</em>
                <?php } ?>
            </div>
        </div>
    </div>
</div>