<a href="<?=$this->url("comic/page", ['pageUrl' => $page->url])?>">
    <img
        title="<?=$page->name?>"
        src="http://<?=$this->siteParam("comic-s3-bucket")?>/<?=$page->image->fileName?> - 512x512.<?=$page->image->fileExtension?>"
    />
    <?php if($this->siteParam("comic-show-archive-page-names")) { ?>
        <br/><span><em><?=$page->name?></em></span>
    <?php } ?>
</a>
