<ul class="comic-nav-links">
	<?php if(!$node->isFirst()) { ?>
		<li>
			<a href="<?=$this->url('comic/page', $node->arc->firstNode()->getRoutingData())?>">&lt;&lt;</a>
		</li>
		<li>
			<a href="<?=$this->url('comic/page', $node->prevNode()->getRoutingData())?>">&lt;</a>
		</li>
	<?php } else { ?>
		<li class="arc-link prev-arc-link">
			<?php if($node->hasPrevArc()) { ?>
				<a href="<?=$this->url('comic/page', $node->arc->prevArc->lastNode()->getRoutingData())?>">&lt; <?=$node->arc->prevArc->displayName()?></a>
			<?php } ?>
		</li>
	<?php } ?>
	<li class="arc-page-list">
		<?php if($this->siteParam('comic-show-archive-dropdown')) { ?>
			<select>
				<option data-url=""><?=$node->arc->fullName()?></option>
				<?php foreach($node->arc->getPageNodes() as $curNode) { ?>
					<option data-url="<?=$this->url("comic/page", $curNode->getRoutingData())?>">(<?=$curNode->pageNumber?>) <?=$curNode->page->title?></option>
				<?php } ?>
			</select>
		<?php } else { ?>
			<a href="<?=$this->url('comic/archives', array('arc' => $node->arc->url))?>" title="<?=$node->arc->fullName()?>">
				<?=$node->arc->name?>
			</a>
		<?php } ?>
	</li>
	<?php if(!$node->isLast()) { ?>
		<li>
			<a href="<?=$this->url('comic/page', $node->nextNode()->getRoutingData())?>">&gt;</a>
		</li>
		<li>
			<a href="<?=$this->url('comic/page', $node->arc->lastNode()->getRoutingData())?>">&gt;&gt;</a>
		</li>
	<?php } else { ?>
		<li class="arc-link next-arc-link">
			<?php if($node->hasNextArc()) { ?>
				<a href="<?=$this->url('comic/page', $node->arc->nextArc->firstNode()->getRoutingData())?>"><?=$node->arc->nextArc->displayName()?> &gt;</a>
			<?php } ?>
		</li>
	<?php } ?>
</ul>
