<ul class="comic-nav-links">
	<?php if(!$node->isFirstNode()) { ?>
		<li>
			<a href="<?=$this->basePath($node->arc->firstNode()->fullUrl())?>">&lt;&lt;</a>
		</li>
		<li>
			<a href="<?=$this->basePath($node->prevNode->fullUrl())?>">&lt;</a>
		</li>
	<?php } else { ?>
		<li class="arc-link">
			<?php if($node->hasPrevArc()) { ?>
				<a href="<?=$node->arc->prevArc->lastNode()->fullUrl()?>">&lt; <?=$node->arc->prevArc->displayName()?></a>
			<?php } ?>
		</li>
	<?php } ?>
	<li class="arc-name">
		<?=$node->arc->fullName()?>
	</li>
	<?php if(!$node->isLastNode()) { ?>
		<li>
			<a href="<?=$this->basePath($node->nextNode->fullUrl())?>">&gt;</a>
		</li>
		<li>
			<a href="<?=$this->basePath($node->arc->lastNode()->fullUrl())?>">&gt;&gt;</a>
		</li>
	<?php } else { ?>
		<li class="arc-link">
			<?php if($node->hasNextArc()) { ?>
				<a href="<?=$node->arc->nextArc->firstNode()->fullUrl()?>"><?=$node->arc->nextArc->displayName()?> &gt;</a>
			<?php } ?>
		</li>
	<?php } ?>
</ul>
